# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/CaesarKasiba/ML-Pipeline/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

My chosen lane is Lane 2: Refresh / Content Opportunity Scoring. I frame this primarily as a ranking problem: the goal is to rank content pages by their potential priority for human review and possible refresh.

The decision is not simply whether a page is "good" or "bad." A content team has limited time, so the useful output is an ordered list that helps them decide which pages to investigate first. The ranking would use observable page, search, engagement, and freshness signals to identify pages that appear more worthy of review.

In [21]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*


The real-world outcome I care about is whether a content page is worth prioritizing for review and potential refresh. The starter dataset does not contain a direct label for "refresh opportunity," so I would use an observable performance outcome as a proxy.

My provisional target is future change in page search performance. The idea is to use information available about a page at the decision point to rank pages according to their subsequent performance change. The exact target window and threshold will need to be defined carefully to avoid leakage and to ensure that features are available before the outcome being predicted.

For this framing exercise, I treat the target as a proxy rather than claiming that it directly represents the true causal value of refreshing a page.

In [22]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Success metric

*One metric you can defend. What number means 'good'?*


My primary success metric will be Precision@50. The practical decision is which pages should be reviewed first, and a content team has limited capacity. Precision@50 therefore measures how useful the top 50 recommendations are according to the chosen target definition.

A higher Precision@50 would mean that a larger proportion of the highest-priority pages correspond to the outcome we are trying to identify. I would also compare the model against a simple baseline/rule so that improvement is measured against something practical rather than assuming that any model is automatically useful.

In [23]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [24]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

import pandas as pd

url = "https://raw.githubusercontent.com/CaesarKasiba/ML-Pipeline/main/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(url)

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [25]:
lane_df = df[
    [
        "content_id",
        "client_id",
        "content_type",
        "content_age_days",
        "impressions_90d",
        "clicks_90d",
        "ctr",
        "avg_position",
        "engagement_rate",
        "trend_direction",
        "trend_pct"
    ]
].copy()

lane_df.head(10)

,content_id,client_id,content_type,content_age_days,impressions_90d,clicks_90d,ctr,avg_position,engagement_rate,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,keyword article,187,3803,29,0.76,10.6,5.88,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,keyword article,445,15320,7,0.05,20.3,0.00,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,keyword article,141,12581,11,0.09,36.5,0.00,down,-60.9
3,content_331d6c4de07b,client_19581e27de,keyword article,463,11751,58,0.49,6.2,1.28,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,keyword article,263,19140,24,0.13,44.0,0.00,down,-34.7
5,content_d4084a4bc775,client_f369cb89fc,keyword article,147,3970,1,0.03,8.5,0.00,down,-38.9
6,content_9a34b442b552,client_8722616204,keyword article,90,20,0,0.00,7.0,0.00,down,-92.3
7,content_a63219c6e95a,client_19581e27de,keyword article,445,1724,1,0.06,21.2,3.57,stable,0.6
8,content_5e6c160719bc,client_6208ef0f77,keyword article,90,32574,29,0.09,46.0,5.88,down,-58.8
9,content_c27558df2b0c,client_19581e27de,keyword article,257,1240,2,0.16,4.9,0.00,down,-29.2

In [26]:
print("One row represents one content page.")
print("Number of rows:", len(lane_df))
print("Unique content IDs:", lane_df["content_id"].nunique())

One row represents one content page.
Number of rows: 30000
Unique content IDs: 30000

In [27]:
lane_df["provisional_target"] = (
    lane_df["trend_direction"] == "down"
).astype(int)

lane_df[
    [
        "content_id",
        "trend_direction",
        "trend_pct",
        "provisional_target"
    ]
].head(10)

             content_id trend_direction  trend_pct  provisional_target
0  content_304f48230142            down      -41.4                   1
1  content_a1fb4e703a9e            down      -57.7                   1
2  content_9aa793d4d895            down      -60.9                   1
3  content_331d6c4de07b          stable      -13.8                   0
4  content_d99b7a2d90ca            down      -34.7                   1
5  content_d4084a4bc775            down      -38.9                   1
6  content_9a34b442b552            down      -92.3                   1
7  content_a63219c6e95a          stable        0.6                   0
8  content_5e6c160719bc            down      -58.8                   1
9  content_c27558df2b0c            down      -29.2                   1

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*


A simple fixed rule could identify pages for review using a single signal, such as selecting every page with a downward trend. However, this would produce a large group of candidates and would treat pages with very different characteristics in the same way.

A learned ranking approach could combine multiple signals such as impressions, CTR, average position, content age, engagement, content type, and search demand. This may allow the system to prioritize pages more selectively than a single threshold or rule.

ML is therefore useful here not because a model is automatically better than a rule, but because the decision involves multiple interacting signals and the team needs a prioritized list rather than a simple yes/no rule. The model would still need to demonstrate improvement over a sensible baseline before it would be considered useful.

In [28]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

## Final note
The model would rank pages according to a defined performance-based proxy for refresh opportunity